# 异常

每个异常用类`Throwable`或其子类（总是非泛型的）的实例表示。`Throwable`有两个直接子类：
- `Exception`是通常程序可能期望从中恢复的异常类的超类，它有一个直接子类：
    - `RuntimeException`是求值表达式可能抛出但仍可从中恢复的异常类（称为运行时异常类）的超类
- `Error`是通常程序通常不期望从中恢复的异常类（称为错误类）的超类

其中运行时异常和错误是非检查型异常，其它异常则是检查型异常

抛出异常的情况可分为：
- 执行`throw`语句
- Java虚拟机同步地检测到的非正常条件：
    - 表达式的求值违反Java语言的正常语义，如除以零
    - 在程序的加载、链接或初始化过程中出错，这时抛出`LinkageError`子类的实例
    - 内部错误或资源限制妨碍Java虚拟机实现Java语言的语义，这时抛出`VirtualMachineError`子类的实例
- 可能出现于运行时任意点的异步异常
    - 调用（已过时的）`Thread`或`ThreadGroup`类的`stop`方法可引致一个其它线程或一个线程组中全部线程抛出异常
    - 内部错误或资源限制妨碍Java虚拟机实现Java语言的语义，这时抛出`VirtualMachineError`子类的实例


同一异常类的实例可以代表异步异常或同步异常，如`StackOverflowError`和`OutOfMemoryError`。

Java SE容许在异步异常抛出前执行有界的少量工作以便优化。

# 编译期异常检查

Java语言要求程序包含检查型异常的处理器。每个方法或构造器的`throws`子句是用户与作者的契约的一部分。

- 一个类实例创建表达式可抛出一个异常类当且仅当以下之一成立：
    - 限定表达式可抛出该异常
    - 有参数表达式可抛出该异常
    - 选中构造器的调用类型的异常类型之一是该异常
    - `ClassBody`中实例初始化器或实例变量初始化器可抛出该异常
- 一个类实例创建表达式可抛出一个异常类当且仅当以下之一成立：
    - `Primary . [TypeArguments] Identifier`形式的`Primary`可抛出该异常
    - 有参数表达式可抛出该异常
    - 选中方法的调用类型的异常类型之一是该异常
- lambda表达式不抛出异常类
- 其它类型表达式可抛出一个异常类当且仅当有子表达式可抛出它

- 一个抛出表达式为非`final`非事实上`final`异常参数的`throw`语句可抛出其静态类型和表达式可抛出的异常类
- 一个抛出表达式为`final`或事实上`final`异常参数的`throw`语句可抛出异常类当且仅当：
    - 它是`try`块可抛出的
    - 它赋值兼容于`catch`子句的任何可捕获异常类
    - 它不赋值兼容于同一`try`语句前面`catch`子句的所有可捕获异常类
- 一个`try`语句可抛出一个异常当且仅当以下之一：
    - `try`块可抛出它、资源初始化表达式可抛出它或资源的`close()`方法可抛出它，但它不赋值兼容于任何`catch`子句的可捕获异常类，而且没有`finally`或`finally`块可正常完成
    - 有`catch`块可抛出它，且没有`finally`或`finally`块可正常完成
    - `finally`块可抛出它
- 一个显式构造器调用语句可抛出一个异常当且仅当以下之一：
    - 有参数表达式可抛出它
    - 所调用构造器的招聘子句有它
- 其它语句可抛出一个异常当且仅当它直接包含的语句或表达式或抛出它

以下情况是编译期错误：
- 方法或构造器体可抛出的某个检查型异常不是`throws`子句声明的异常的子类型
- lambda表达式体可抛出的某个检查型异常不是目标函数类型的`throws`子句声明的异常的子类型
- 类变量初始化器或具名类或接口的静态初始化器可抛出检查型异常
- 实例变量初始化器或具名类或接口的实例初始化器可抛出检查型异常，除非声明了显式构造器且所有构造器的`throws`都声明了其超类
- `catch`子句可捕获`try`块不可抛出且不是`Exception`或其超类的检查型异常
- `catch`子句捕获前面`catch`子句捕获的子类型

# 异常处理

抛出异常后，表达式、语句、方法、构造器调用、初始化器和域初始化表达式等等从内而外中止，直到被捕获或者线程的未捕获异常处理器。

抛出异常时，控制转移到动态包围于的引发异常的代码的可处理该异常（有超类型为可捕获异常）的最接近`catch`子句。其中，一个语句或表达式动态包围于一个`catch`子句是指以下之一：
- 它位于`catch`子句所在`try`语句的`try`块
- 它的调用者动态包围于该`catch`子句，其中
    - 在方法中，调用者为导致方法被调用的方法调用表达式
    - 在构造器或实例初始化器或实例变量初始化器中，调用者为导致对象被创建的类实例创建表达式或`newInstance`方法调用
    - 在静态初始化器、静态变量初始化器中，调用者为使用类或接口而导致初始化的表达式

控制通过中止表达式或语句转移直到遇到可处理被抛出异常的`catch`子句，然后执行其`catch`块。所有异常是精确的：当开始转移，异常点之前的语句和表达式的副作用可见，而此后的语句和表达式的副作用不可见。如果没有找到可处理异常的`catch`子句，则当前线程终止。终止前执行所有`finally`子句和按如下规则处理未捕获异常：
- 若当前线程有未捕获异常处理器，则执行之。
- 否则，调用当前线程的父`ThreadGroup`的`uncaughtException`方法